name: Publish Docker image to GHCR

on:
  pull_request:
    types: [ labeled ]

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
