name: Publish Docker image to GHCR

on:
  pull_request:
    types: [ labeled ]

jobs:
  push_image:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == "autorelease: tagged" }}
    steps:
    - uses: actions/checkout@v3
