name: Publish Docker image to GHCR

on:
  release:
    types: [ published ]
  
jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      ssh-key: "${{ secrets.GHCR_DEPLOY_KEY }}"
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_DEPLOY_KEY }}
    - name: Build & push the image
      env:
        REPO: ${{ github.repository }}
      run: |
        VERSION=$(cat version.txt)
        docker build --tag ghcr.io/$REPO:$VERSION --label "org.opencontainers.image.source=https://github.com/$REPO" --label "org.opencontainers.image.version=$VERSION" .
        docker push ghcr.io/$REPO:$VERSION
