name: Create Release PR

on:
  push:
    branches: [ main ]

jobs:
  release_pr:
    runs-on: ubuntu-latest
    steps:
    - id: create
      uses: google-github-actions/release-please-action@v3
      ssh-key: "${{ secrets.GHCR_DEPLOY_KEY }}"
      with:
        release-type: simple
