name: Release
on:
  push:
    branches:
      - main
jobs:
  build-tag-release:
    name: Build, tag, and release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get Release Token
        id: get_release_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - name: Setup release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ steps.get_release_token.outputs.token }}
          release-type: simple
      - uses: docker/login-action@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}
      - name: Build Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker build \
          -t "ghcr.io/${GITHUB_REPOSITORY}:${{ steps.release.outputs.tag_name }}" \
          -t "ghcr.io/${GITHUB_REPOSITORY}:latest" .
      - name: Release Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker push "ghcr.io/${GITHUB_REPOSITORY}:${{ steps.release.outputs.tag_name }}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}:latest"
